apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-application-properties
type: Opaque
stringData:
  application.properties: |
    # Kafka
    spring.kafka.properties.sasl.mechanism=PLAIN
    spring.kafka.properties.bootstrap.servers=pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
    spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='LPRHAVOM2VGMU66L'   password='L4iN11W2HBEeJW48WrPOkhb8kfxuTtjlcF92GlOTev1j8NK2WVkeKOV6TmXUysOW';
    spring.kafka.properties.security.protocol=SASL_SSL
    # Confluent Cloud Schema Registry
    spring.kafka.properties.basic.auth.credentials.source=USER_INFO
    spring.kafka.properties.schema.registry.basic.auth.user.info=ZVDMBDXQQFYHZTVO:Sp/I1WBNjUdffONs1NeevemrZ/MWrU1jaI+2t049G+5VkqlZyW/lBiFF6r1Ox2ru
    spring.kafka.properties.schema.registry.url=https://psrc-j55zm.us-central1.gcp.confluent.cloud

    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
    spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
    my.topics.replication.factor=3
    my.topics.partitions.count=6
  